stages:
  data_streaming:
    cmd: python src/data_streaming.py
    deps:
    - src/data_streaming.py
    outs:
    - src/prepare_data/AMZN_.csv
    - src/prepare_data/Indicateur.csv
    - src/prepare_data/SP500.csv
    
  data_preparation:
    cmd: python src/data_preparation.py
    deps:
    - src/data_preparation.py
    - src/prepare_data/AMZN_.csv
    - src/prepare_data/Indicateur.csv
    - src/prepare_data/SP500.csv
    outs:
    - src/prepare_data/X_data.csv
    - src/prepare_data/y_data.csv

  modeling:
    cmd: python src/modeling.py
    deps:
    - src/modeling.py
    - src/prepare_data/X_data.csv
    - src/prepare_data/y_data.csv
    outs:
    - src/models/RandomForestClassifier_model.pkl

  evaluation:
    cmd: python src/evaluation.py
    deps:
    - src/evaluation.py
    - src/models/RandomForestClassifier_model.pkl

    outs:
    - feature_importances_.png
    - confusion_matrix.png

  


